GET http://localhost:2000/income

###
GET http://localhost:2000/outcome

###
POST  http://localhost:2000/outcome
header:{}
{
    "description": "Home Rent",
    "amount": 1325,
    "category": "housing"
}

###
PATCH  http://localhost:2000/outcome


###
DELETE  http://localhost:2000/outcome


###
GET http://localhost:2000/tracker